!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 11 #total score to pass
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 2, z: 1}
      rotations: [5] #Agent rotation
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} # Platform Position
      rotations: [0] # Platform Rotation
      sizes:
      - !Vector3 {x: 3, y: 2, z: 40} # Platform Size
      colors:
      - !RGB {r: 0, g: 0, b: 256} #Platform Color
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 14.5, y: 0, z: 20} # Ramp Position
      rotations: [270] # Ramp Rotation
      sizes:
      - !Vector3 {x: 40, y: 2, z: 8} # Ramp Size
      colors:
      - !RGB {r: 256, g: 0, b: 256} #Ramp Color
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 5, y: 0, z: 20} #GoodGoalMulti Position
      - !Vector3 {x: 35, y: 0, z: 15} #GoodGoalMulti Position
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 35, y: 0, z: 20} #GoodGoal Position
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoal Size

    blackouts: [-1]
