!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 1 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [5] #Agent Rotation
    - !Item
      name: GoodGoalBounce #GoodGoalName
      positions:
      - !Vector3 {x: 15, y: 0, z: 20} #GoodGoal Position
      rotations: [225] # GoodGoalBounce rotation
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #GoodGoal Size
    - !Item
      name: BadGoalBounce #BadGoalBounceName
      positions:
      - !Vector3 {x: 25, y: 0, z: 20} #BadGoal Position
      rotations: [135] # BadGoalBounce rotation
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #BadGoal Size


    blackouts: [-10]
