!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 7 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [5] #Agent Rotation
    - !Item
      name: GoodGoalMultiBounce #GoodGoalMultiBounceName
      positions:
      - !Vector3 {x: 15, y: 0, z: 20} #GoodGoalMulti Position
      - !Vector3 {x: 25, y: 0, z: 20} #GoodGoalMulti Position
      rotations: [45,315] # GoodGoalMultiBounce rotation
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
    - !Item
      name: BadGoalBounce #BadGoalBounceName
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} #BadGoal Position
      rotations: [135] # BadGoalBounce rotation
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size


    blackouts: [-5]
