!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0 #total score to pass
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0] #Agent rotation
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 22, y: 0, z: 25} #Transparent Wall Position
      - !Vector3 {x: 18, y: 0, z: 25} #Transparent Wall Position
      rotations: [0,0] #Transparent Wall Rotation
      sizes:
      - !Vector3 {x: 3.25, y: 5, z: 1} #Transparent Wall Size
      - !Vector3 {x: 3.25, y: 5, z: 1} #Transparent Wall Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 35} #GoodGoal Position
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoal Size


    blackouts: [-15]
