!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1.4 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent position
      rotations: [0] #Agent rotation
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 15, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 25, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 30, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 10, y: 0, z: 15} #GoodGoalMulti Position
      rotations: [0,0,0,0]  #GoodGoalMulti rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalMulti Size
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalMulti Size
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalMulti Size
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalMulti Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 15}  #GoodGoal Position
      rotations: [0]  #GoodGoal rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoal Size

    blackouts: [-10]
