!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0.5 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 2, z: 5} #Agent Position
      rotations: [-1]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [-1,-1,-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [-1,-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
 # No rotations specified - will be randomised
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 9, y: 0, z: 10} # Wall Position
      - !Vector3 {x: 31, y: 0, z: 10} # Wall Position
      - !Vector3 {x: 17.78, y: 0, z: 30} # Wall Position
      - !Vector3 {x: 22.22, y: 0, z: 30} # Wall Position
      - !Vector3 {x: 20, y: 0, z: 10} # Wall Position
      - !Vector3 {x: 18.25, y: 0, z: 1} # Wall Position
      - !Vector3 {x: 21.75, y: 0, z: 1} # Wall Position
      rotations: [45, 135, 258.7, 101.3,0, 0, 0] # Wall Rotations
      colors:
       - !RGB {r: 153, g: 153, b: 153} # Wall Color
       - !RGB {r: 153, g: 153, b: 153} # Wall Color
       - !RGB {r: 153, g: 153, b: 153} # Wall Color
       - !RGB {r: 153, g: 153, b: 153} # Wall Color
       - !RGB {r: 0, g: 0, b: 256} # Wall Color
       - !RGB {r: 153, g: 153, b: 153} # Wall Color
       - !RGB {r: 153, g: 153, b: 153} # Wall Color
      sizes:
      - !Vector3 {x: 24.2, y: 5, z: .5} # Wall Size
      - !Vector3 {x: 24.2, y: 5, z: .5} # Wall Size
      - !Vector3 {x: 20, y: 5, z: .5} # Wall Size
      - !Vector3 {x: 20, y: 5, z: .5} # Wall Size
      - !Vector3 {x: 3, y: 2, z: 20} # Wall Size
      - !Vector3 {x: 0.5, y: 5, z: 2} # Wall Size
      - !Vector3 {x: 0.5, y: 5, z: 2} # Wall Size
    blackouts: [-20]
