!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [355] #Agent Rotation
    - !Item
      name: GoodGoalBounce #GoodGoalName
      positions:
      - !Vector3 {x: 15, y: 0, z: 15} #GoodGoalBounce Position
      rotations: [90] # GoodGoalBounce rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalBounce Size
    - !Item
      name: GoodGoalMultiBounce #GoodGoalMultiBounceName
      positions:
      - !Vector3 {x: 20, y: 0, z: 15} #GoodGoalMultiBounce Position
      rotations: [90] # GoodGoalMultiBounce rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalMultiBounce Size
    - !Item
      name: BadGoalBounce #BadGoalBounce Name
      positions:
      - !Vector3 {x: 25, y: 0, z: 15} #BadGoalBounce Position
      rotations: [90] # BadGoalBounce rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #BadGoalBounce Size


    blackouts: [-10]
