!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 2, z: -1} #Agent Position
      rotations: [-1]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} # Platform Position
      rotations: [0] # Platform Rotation
      sizes:
      - !Vector3 {x: 3, y: 2, z: 40} # Platform Size
      colors:
      - !RGB {r: 0, g: 0, b: 256} #Platform Color
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 25.5, y: 0, z: 20} # Ramp Position
      rotations: [90] # Ramp Rotation
      sizes:
      - !Vector3 {x: 40, y: 2, z: 8} # Ramp Size
      colors:
      - !RGB {r: 256, g: 0, b: 256} #Ramp Color
    blackouts: [-5]
