!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0 #total score to pass
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [355] #Agent rotation
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 10.5, y: 0, z: 20} # 1 Lava Position
      - !Vector3 {x: 29.5, y: 0, z: 25} # 2 Lava Position
      rotations: [0,0] # Lava Rotation
      sizes:
      - !Vector3 {x: 21, y: 0.1, z: 1} # Lava Size
      - !Vector3 {x: 21, y: 0.1, z: 1} # Lava Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 37.5} #GoodGoal Position
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoal Size


    blackouts: [-10]
