!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: -1.5
    t: 500
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: 20, y: 0, z: 20}
        rotations: [0]
    blackouts: [-20]
