!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 30 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [355] #Agent Rotation
    - !Item
      name: GoodGoalMultiBounce #GoodGoalMultiBounceName
      positions:
      - !Vector3 {x: 12.5, y: 0, z: 12.5} #GoodGoalMulti Position
      - !Vector3 {x: 22.5, y: 0, z: 12.5} #GoodGoalMulti Position
      - !Vector3 {x: 17.5, y: 0, z: 17.5} #GoodGoalMulti Position
      - !Vector3 {x: 27.5, y: 0, z: 17.5} #GoodGoalMulti Position
      - !Vector3 {x: 12.5, y: 0, z: 22.5} #GoodGoalMulti Position
      - !Vector3 {x: 22.5, y: 0, z: 22.5} #GoodGoalMulti Position
      - !Vector3 {x: 17.5, y: 0, z: 27.5} #GoodGoalMulti Position
      - !Vector3 {x: 27.5, y: 0, z: 27.5} #GoodGoalMulti Position
      rotations: [225,135,270,90,315,45,0,90] # GoodGoalMultiBounce rotation
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoalMulti Size
    - !Item
      name: BadGoalBounce #BadGoalBounceName
      positions:
      - !Vector3 {x: 17.5, y: 0, z: 12.5} #BadGoal Position
      - !Vector3 {x: 27.5, y: 0, z: 12.5} #BadGoal Position
      - !Vector3 {x: 12.5, y: 0, z: 17.5} #BadGoal Position
      - !Vector3 {x: 22.5, y: 0, z: 17.5} #BadGoal Position
      - !Vector3 {x: 17.5, y: 0, z: 22.5} #BadGoal Position
      - !Vector3 {x: 27.5, y: 0, z: 22.5} #BadGoal Position
      - !Vector3 {x: 12.5, y: 0, z: 27.5} #BadGoal Position
      - !Vector3 {x: 22.5, y: 0, z: 27.5} #BadGoal Position
      rotations: [225,135,270,90,315,45,0,90] # BadGoalBounce rotation
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoal Size


    blackouts: [-10]
