!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0 #total score to pass
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [5] #Agent rotation
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 22, y: 0, z: 17.5} # Wall Position
      - !Vector3 {x: 18, y: 0, z: 17.5} # Wall Position
      rotations: [0,0] # Wall Rotation
      sizes:
      - !Vector3 {x: 3.25, y: 5, z: 1} # Wall Size
      - !Vector3 {x: 3.25, y: 5, z: 1} # Wall Size
      colors:
      - !RGB {r: 153, g: 153, b: 153} #Wall Color
      - !RGB {r: 153, g: 153, b: 153} #Wall Color
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 30} #GoodGoal Position
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoal Size


    blackouts: [-5]
