!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 6.9 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent position
      rotations: [355] #Agent rotation
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 12.5, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 27.5, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 22.5, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 17.5, y: 0, z: 15} #GoodGoalMulti Position
      rotations: [0,0,0,0]  #GoodGoalMulti rotation
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti Size
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti Size
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti Size
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 7.5, y: 0, z: 15}  #GoodGoal Position
      - !Vector3 {x: 32.5, y: 0, z: 15}  #GoodGoal Position
      rotations: [0,0]  #GoodGoal rotation
      sizes:
      - !Vector3 {x: 0.25, y: 0.25, z: 0.25} #GoodGoal Size
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoal Size

