!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 3 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [0] #Agent Rotation
    - !Item
      name: GoodGoal #GoodGoalName
      positions:
      - !Vector3 {x: 15, y: 0, z: 15} #GoodGoal Position
      rotations: [0] # GoodGoal rotation
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #GoodGoal Size
    - !Item
      name: GoodGoalMulti #GoodGoalMultiName
      positions:
      - !Vector3 {x: 20, y: 0, z: 15} #GoodGoalMulti Position
      rotations: [0] # GoodGoalMulti rotation
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #GoodGoalMulti Size
    - !Item
      name: BadGoal #BadGoal Name
      positions:
      - !Vector3 {x: 25, y: 0, z: 15} #BadGoal Position
      rotations: [0] # BadGoal rotation
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #BadGoal Size

    blackouts: [-20]
