!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0 #total score to pass
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [355] #Agent rotation
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 10.5, y: 0, z: 17.5} # Lava Position
      - !Vector3 {x: 29.5, y: 0, z: 12.5} # Lava Position
      rotations: [0,0] # Lava Rotation
      sizes:
      - !Vector3 {x: 21, y: 0.1, z: 1} # Lava Size
      - !Vector3 {x: 21, y: 0.1, z: 1} # Lava Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 30} #GoodGoal Position
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoal Size


    blackouts: [-15]
