!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 2 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [5] #Agent Rotation
    - !Item
      name: GoodGoal #GoodGoalName
      positions:
      - !Vector3 {x: 22.5, y: 0, z: 15} #GoodGoal Position
      rotations: [0] # GoodGoal rotation
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoal Size
    - !Item
      name: GoodGoalMulti #GoodGoalMultiName
      positions:
      - !Vector3 {x: 27.5, y: 0, z: 15} #GoodGoalMulti Position
      - !Vector3 {x: 12.5, y: 0, z: 15} #GoodGoalMulti Position
      rotations: [0,0] # GoodGoalMulti rotation
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti Size
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMulti Size
    - !Item
      name: BadGoal #BadGoal Name
      positions:
      - !Vector3 {x: 7.5, y: 0, z: 15} #BadGoal Position
      - !Vector3 {x: 17.5, y: 0, z: 15} #BadGoal Position
      - !Vector3 {x: 32.5, y: 0, z: 15} #BadGoal Position
      rotations: [0,0,0] # BadGoal rotation
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #BadGoal Size
      - !Vector3 {x: 1, y: 1, z: 1} #BadGoal Size
      - !Vector3 {x: 1, y: 1, z: 1} #BadGoal Size

    blackouts: [-5]
