!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [5] #Agent Rotation
    - !Item
      name: GoodGoalBounce #GoodGoalName
      positions:
      - !Vector3 {x: 25, y: 0, z: 15} #GoodGoalBounce Position
      rotations: [90] # GoodGoalBounce rotation
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2} #GoodGoalBounce Size
    - !Item
      name: GoodGoalMultiBounce #GoodGoalMultiBounceName
      positions:
      - !Vector3 {x: 20, y: 0, z: 15} #GoodGoalMultiBounce Position
      rotations: [90] # GoodGoalMultiBounce rotation
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMultiBounce Size
    - !Item
      name: BadGoalBounce #BadGoalBounce Name
      positions:
      - !Vector3 {x: 15, y: 0, z: 15} #BadGoalBounce Position
      rotations: [90] # BadGoalBounce rotation
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoalBounce Size



    blackouts: [-20]
