!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 8.9 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [355]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 17, y: 0, z: 35}
      - !Vector3 {x: 13, y: 0, z: 4}
      - !Vector3 {x: 23, y: 0, z: 30}
      - !Vector3 {x: 10, y: 0, z: 25}
      - !Vector3 {x: 30, y: 0, z: 17}
      - !Vector3 {x: 6, y: 0, z: 22}
      - !Vector3 {x: 37, y: 0, z: 13}
      - !Vector3 {x: 36, y: 0, z: 32}
      - !Vector3 {x: 18, y: 0, z: 10}
      - !Vector3 {x: 24, y: 0, z: 18}
      rotations: [0,0,0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
      - !Vector3 {x: 1, y: 1, z: 1}
