!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: -1.5
    t: 500
    items:
      - !Item
        name: Agent
        positions:
        - !Vector3 {x: -1, y: -1, z: -1}
        rotations: [-1]
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
 # No rotations, sizes, or colors specified - will be randomised

    blackouts: [-1]
