!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0 #End
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1]
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      rotations: [-1]
      sizes:
      - !Vector3 {x: -1, y: -1, z: -1}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
      - !Vector3 {x: -1, y: -1, z: -1}
 # No rotations, sizes, or colors specified - will be randomised
    blackouts: [-1]
