!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2.5 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [90] #Agent Rotation
    - !Item
      name: GoodGoalBounce #GoodGoalName
      positions:
      - !Vector3 {x: 22.5, y: 0, z: 15} #GoodGoalBounce Position
      rotations: [90] # GoodGoalBounce rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalBounce Size
    - !Item
      name: GoodGoalMultiBounce #GoodGoalMultiBounceName
      positions:
      - !Vector3 {x: 27.5, y: 0, z: 15} #GoodGoalMultiBounce Position
      - !Vector3 {x: 12.5, y: 0, z: 15} #GoodGoalMultiBounce Position
      rotations: [90,270] # GoodGoalMultiBounce rotation
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1} #GoodGoalMultiBounce Size
      - !Vector3 {x: 2, y: 2, z: 2} #GoodGoalMultiBounce Size
    - !Item
      name: BadGoalBounce #BadGoalBounce Name
      positions:
      - !Vector3 {x: 7.5, y: 0, z: 15} #BadGoalBounce Position
      - !Vector3 {x: 17.5, y: 0, z: 15} #BadGoalBounce Position
      - !Vector3 {x: 32.5, y: 0, z: 15} #BadGoalBounce Position
      rotations: [45, 135,315] # BadGoalBounce rotation
      sizes:
      - !Vector3 {x: 0.25, y: 0.25, z: 0.25} #BadGoalBounce Size
      - !Vector3 {x: 3, y: 3, z: 3} #BadGoalBounce Size
      - !Vector3 {x: 4, y: 4, z: 4} #BadGoalBounce Size

    blackouts: [-1]
