!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0.5 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 5, z: 1}
      rotations: [-1]
    - !Item
      name: GoodGoalMultiBounce
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [-1,-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      rotations: [-1,-1,-1]
      sizes:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
    - !Item
      name: BadGoalBounce
      positions:
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
      - !Vector3 {x: -1, y: 5, z: -1}
 # No rotations specified - will be randomised
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 25} # Platform Position
      rotations: [0] # Platform Rotation
      sizes:
      - !Vector3 {x: 40, y: 1.5, z: 30} # Platform Size
      colors:
      - !RGB {r: 0, g: 0, b: 256} #Platform Color
    - !Item
      name: Ramp
      positions:
      - !Vector3 {x: 20, y: 0, z: 7.5} # Ramp Position
      rotations: [180] # Ramp Rotation
      sizes:
      - !Vector3 {x: 20, y: 1.5, z: 5} # Ramp Size
      colors:
      - !RGB {r: 256, g: 0, b: 256} #Ramp Color
    blackouts: [-5]
