!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: -0.5 #total score to pass
    t: 750
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1} #Agent Position
      rotations: [355] #Agent Rotation
    - !Item
      name: GoodGoal #GoodGoalName
      positions:
      - !Vector3 {x: 15, y: 0, z: 20} #GoodGoal Position
      rotations: [0] # GoodGoal rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoal Size
    - !Item
      name: GoodGoalMulti #GoodGoalMultiName
      positions:
      - !Vector3 {x: 25, y: 0, z: 20} #GoodGoalMulti Position
      rotations: [0] # GoodGoalMulti rotation
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5} #GoodGoalMulti Size


    blackouts: [-1]
